homeassistant:
  name: Nashville School of Law
  latitude: 36.103461
  longitude: -86.7626287
  elevation: 0
  unit_system: imperial
  time_zone: America/Chicago

# Enables the frontend
frontend:

# Enables configuration UI
config:

# View all events in a logbook
logbook:

lovelace:
  mode: yaml

variable:
  whispers:
    value: 'Applied'
    attributes:
      friendly_name: 'Interesting Request'
      hostnames: ''
      counts: ''
      icon: mdi:chat
    restore: true
