repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: debug-statements
      - id: check-executables-have-shebangs
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=120']
